### PR TITLE
New spec 0.2.1

### PR DESCRIPTION
**Pull request by keighrim**
This PR prepares a release candidate for 0.2.1 in the `develop` branch.

### CODE REVIEW

**Comment by keighrim** [comment]
Tests fail as the updated python code is not included in this PR. Code updates will follow as a separate PR.

**Review by marcverhagen — COMMENTED** [review]
Looks good to me in general. There may be instances of 0.2.0 at other spots but for now not finding them is okay. Also, I think I want to update the publish script because some of the files in docs/0.2.1 need not be published.

**Comment by keighrim** [comment]
@marcverhagen do you want that for 0.2.1, or for the future version?

**Comment by marcverhagen** [comment]
It's not too bad, and I don't want to fix it right now, so let's have that for a next version.

**Review by marcverhagen — APPROVED** [review]

**Pull request merged**
