### PR TITLE
adding `get_documents_by_type`

### PR DESCRIPTION
**Pull request by keighrim**
addressing #126.

### CODE REVIEW

**Review by marcverhagen — COMMENTED** [review]
A few notes

- Replace first line of docstring with something like "Method to get all documents where the type matches a particular document type, which should be one of the CLAMS document types."
- Why limit this to just the TextDocument type? That would be appropriate for `get_text_documents()`, but this one is more general and I may want to get all the VideoDocuments. Also, we may allow other documents in the annotations list (unlikely to be useful though). I do not know whether we specifically disallow other documents in the annotations list.
- Does this do the right thing with versions? The value of `DocumentTypes.TextDocument` is 'http://mmif.clams.ai/HEAD/vocabulary/TextDocument', which is not what we will see in the type probably. Maybe match on the basename of the URL.
- I am not too wild either about changing the document id, but see no better solution. Would a resereved name clash with potential properties? Or maybe the method could return a dictionary indexed on doc_id and view_id:doc_id strings.

**Comment by angus-lherrou** [comment]
- The TextDocument check is only for checking within views, since the only Document type we would expect to see in a view is TextDocument. The method always checks the full contents of the documents list.
 - The HEAD version happens when you're running a dev version. If the contents of VERSION doesn't contain `.dev`, it will use the actual version number. The enums get written at build time, which is why you see HEAD locally.
 - I agree that changing the document id isn't great. Reserved names shouldn't clash with potential properties, since it would be a top-level attribute of the Annotation/Document object, which is currently a closed class (currently just `@type` and `properties`).

**Comment by angus-lherrou** [comment]
To elaborate on the name clash point, setting properties is done with the `add_property` method or by accessing the `properties` attribute, not by using `__setitem__` directly on an Annotation or Document object, so there is nowhere for the conflict to occur.

**Comment by marcverhagen** [comment]
> The HEAD version happens when you're running a dev version. If the contents of VERSION doesn't contain .dev, it will use the actual version number. The enums get written at build time, which is why you see HEAD locally.

Ah, didn't realize I was running a dev version. 

One decision to make is whether we want "http://mmif.clams.ai/0.1.0/vocabulary/TextDocument" to match "http://mmif.clams.ai/0.1.1/vocabulary/TextDocument" or "http://mmif.clams.ai/2.0.8/vocabulary/TextDocument". 

I would say yes.

**Comment by keighrim** [comment]
Yeah, I remember we talked about only allowing `TextDocument` within the view::annotations list. It's just removal of one line that make the method work for other types of documents, but I thought 'if the queried type is not `TextDocument`, why bother iterating all view and all annotations? '. 

On the document ID, I also don't think changing the ID on the fly is a good idea. When the input MMIF is *frozen*, it could complicate situation even worse. Having a *hidden* attribute that stores parent viewID, while not showing up in the serialized string could be a workaround for now until we find a better solution. 

Finally, on the compatibility of IRI's, I think we should only consider the major number (first number) when checking compatibility, as minor updates must be backward compatible, while major updates mean that they can (and probably will) break things even though some part (e.g. `TextDocument`) would remain the same, and the SDK have no way to know which part of new major version keeps the legacy.

**Comment by angus-lherrou** [comment]
The compatibility question is already a bit complicated, with the `contains` object in views. The `View._find_match_hotfix` method checks for matches based on the basename of the IRI instead of the full IRI when adding an `@type` to a view's `contains`. So the codebase as it currently stands is inconsistent on the question of what counts as the "same" type. That's something to codify soon.

**Comment by marcverhagen** [comment]
> but I thought 'if the queried type is not TextDocument, why bother iterating all view and all annotations? '.

Fair point, but that would result in the method meaning two things: (1) give me all documents of type TextDocument in the documents list and the views, and (2) only give me documents of other types from the documents list and not the views. That makes the return value of this method depend on us deciding what is allowed in views, when we change that the method needs to be changed. If we decide, which we may have done for now implicitly, that there are only text documents in views, then it won't hurt to check the views anyway because there won't any. I prefer that extra minor processing over having to change the method when we change our minds.

> Finally, on the compatibility of IRI's, I think we should only consider the major number (first number) when checking compatibility, as minor updates must be backward compatible, while major updates mean that they can (and probably will) break things even though some part (e.g. TextDocument) would remain the same, and the SDK have no way to know which part of new major version keeps the legacy.

The compatibility is on the internals, not on the fact that something is a text document. We could have optional parameters specifying that we want to match the major version. When major versions change it may not be because of the document types but because of something else. There is a wider issue here, which is how we deal with pipelines with tools that are primed to different MMIF versions.

**Comment by keighrim** [comment]
More commits added to address issues discussed in the above. I think version compatibility of `@type` values requires a separate issue of its own for further discussion, so this PR doesn't do anything on that.

**Pull request merged**
