### PR TITLE
Adding the ability to freeze the media list

### PR DESCRIPTION
**Pull request by angus-lherrou**
**Note:** I am leaving this as a draft PR towards `develop` for now instead of towards `86-vocabulary-redesign` because it is based off of the recent large refactoring from #82, which is present in `develop` but not in `86-vocabulary-redesign`.

----

This PR changes the mmif-python SDK to make the `media` list immutable by default.

If we decide in #86 that the `media` (or `documents` if we rename it) list should be read-only, this implements that feature. It allows a `Mmif` object to be instantiated with `frozen=False` for use in creation of new MMIF at the source of a pipeline.

If we decide against making `media`/`documents` read-only, these changes could be scrapped or we could decide to implement them partially or optionally.

----

API changes:

- adds a new class, `FreezableMmifObject`, that can be subclassed from instead of `MmifObject`. Classes that extend `FreezableMmifObject` will have a new reserved attribute `_frozen`, and will have access to `is_frozen()`, `freeze()` and `deep_freeze()`.
**Note:** henceforth, anything that implements `FreezableMmifObject` will be referred to adjectivally as "Freezable".
  - `FreezableMmifObject.freeze()` will make the instance shallowly immutable, preventing assignment to all top-level attributes and the use of `__setitem__`, however implemented.
    - `__setitem__` prevention may need more work if it is defined in the same class that implements `FreezableMmifObject` instead of in a base class such as `MmifObject` or `DataList`.
  - `FreezableMmifObject.deep_freeze()` will make the instance deeply immutable, shallowly freezing the current object and additionally deeply freezing all Freezable attributes and Freezable members in dicts, lists, and `DataList`s contained within. If the deep freeze encounters any mutable members that it cannot freeze, it will return `False` (else, `True`). This can give the end user some idea of whether the object they just froze is still mutable in some places, though this is not a contract as it relies on (non-trivial) hashability to determine immutability and mutable objects can be made to be hashable.
    - This method needs work and more testing to prevent manual mutation of the `_unnamed_attributes` dictionary and to deeply traverse any nested vanilla data structures contained within.
  - `FreezableMmifObject.is_frozen()` returns the value of the `_frozen` attribute. This returns `True` if the object is *at least* shallowly frozen.
- renames the `Submedia` class to `Submedium` to more accurately reflect its purpose, as a representation of a single submedium in the `Medium.submedia`.
- adds a new class, `SubmediaList`, which is a Freezable `DataList[Submedium]`.
- changes `Medium.submedia` from `List[Submedium]` to `SubmediaList`.
- makes `Medium`, `MediumMetadata`, `Text`, and `Submedium` in `medium.py` all Freezable.
- makes `MediaList` in `mmif.py` Freezable.
- changed the `validate` flag in `Mmif.__init__` to be a keyword-only parameter.
- adds a new `frozen` flag to `Mmif.__init__`, which is a keyword-only parameter and is set to `True` by default.
  - When this flag is set to True, the `media` list is frozen immediately after deserialization.
  - This flag should only be set to False when populating a new MMIF file at the start of a CLAMS pipeline.
- adds the `freeze_media()` method to `Mmif`, which freezes the `media` list.
- `Mmif.add_medium` will raise a `TypeError` if the `media` list is frozen.

### CODE REVIEW

**Comment by angus-lherrou** [comment]
Changelog for commit 887b3d93359d4ba8b28a00be0517c0af68525ecb :

- Added `DataDict` class to allow wrapping of dictionaries so that the `"contains"` dict can be implemented as Freezable, as the `ContainsDict` class (may revert and change to a regular subclass of `MmifObject`)
   - Implemented handy `dict` methods such as `items()`, `keys()`, and `values()` that just call the same on the internal `_items` dictionary
- Changed `ViewMetadata.contains` from `Dict[str, Contain]` to `ContainsDict` accordingly
- Renamed the `items` attribute in `DataList`s and `DataDict`s to `_items` to avoid conflict with `dict.items()` and generally discourage user access
- Added `_deserialize()` to both `DataList` and `DataDict` that raises a `NotImplementedError` to prevent use of `DataList[T]` or `DataDict[T]` directly instead of subclassing and implementing `_deserialize()`.
- Implemented `View`s and `Annotation`s and relevant component types as Freezable
- Changed the implementation of `deep_freeze()` to descend into nested data structures
   - Changed unit tests to use `frozen=False` in several places in order to test functionality (this was needed now instead of earlier because of an oversight in the old implementation of `deep_freeze()` that allowed these old tests to pass).
- `Mmif.__init__(..., frozen=True)` now freezes all existing `View`s after deserializing
- Added `Mmif.freeze_views()` method
- Added tests for freezing Views

**Comment by keighrim** [comment]
As we indeed decided to make at least primary `documents` list immutable, so we now want to proceed with this PR. The change log seems good enough to proceed, except for that submedia (or submedium) is dropped as of 0.2.0. Maybe we can get rid of or mend code related to submedia after we merge this PR via a separate issue. Up to you.

**Comment by angus-lherrou** [comment]
I'm still working on thorough testing and tweaking of `deep_freeze()`. I'd like your thoughts on how much we want to lock things down versus basically saying "if you use something other than our API to mutate these objects, it's your fault". The more I test and tweak, the more I find ways that mutability can slip through the cracks.

You know, while I was writing this comment, I remembered that our `requirements.txt` has a line for the Pyrsistent package. This is actually something we might be able to use here, since it offers immutable data structures as drop-in replacements (and then some) for standard library lists and dicts. I don't think it's currently used anywhere in the codebase, so I had totally forgotten about it until now, but it'd be super handy here.

What do you think? I'm free all morning to draft up a version of this using Pyrsistent, but I can also keep going with my current strategy of "heavily suggested immutability" (since really that's all we can get with Python anyway) and we could drop Pyrsistent as a dependency.

**Comment by keighrim** [comment]
Interesting. I didn't that pyrsistent was in the requirements (in fact, I didn't know the existence of the library until now). It's prebably gotten there as a dependency of another. So it is quite likely that we are already using pyrsistent anyway, and if it helps we should make use of it, I think.

**Comment by marcverhagen** [comment]
>  I'd like your thoughts on how much we want to lock things down versus basically saying "if you use something other than our API to mutate these objects, it's your fault". The more I test and tweak, the more I find ways that mutability can slip through the cracks.

Yes, I would go with that. I don't think we can force immutability on developers who try to avoid it. So as long as using the API of our SDK prohibits changing things that we don't want changed it should be fine.

**Comment by angus-lherrou** [comment]
Changelog for commit 56a520d13ac2d3c10ea587143bbfed4df07651ab:

 - Changed `reversed_names` to `reserved_names`.
 - Added `'reserved_names'` to `reserved_names`.
 - Reimplemented some features to use Pyrsistent data structures:
   - `MmifObject._attribute_classes` is now a `PMap` instead of a `dict`
   - `reserved_names` is now a `PSet` instead of a list
 - Added `FreezableDataList[T]` and `FreezableDataDict[T]` types to improve abstraction of mixing freezability into `DataList[T]` and `DataDict[T]`
 - Refactored `mmif.MediaList`, `view.AnnotationsList`, `view.ContainsDict`, and `media.SubmediaList` to inherit from these types
 - Changed `MmifObject.__setitem__`, `DataList.__setitem__, and `DataDict.__setitem__` to raise a `KeyError` when attempting to set a name in `reserved_names`.
   - The latter two classes just call up to `MmifObject.__setitem__()` in those cases, which adds an extra PSet membership lookup (![O[log32(n)]](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Cmathcal%7BO%7D%5B%5Clog_%7B32%7D%28n%29%5D)) but improves stack trace clarity.
 - Changed `DataList` and `DataDict` to add `_items` to `reserved_names` and disallow additional properties
 - Added optional `alt_container` parameter to `MmifObject._serialize` for use by `DataList`s and `DataDict`s when serializing `_items` instead of `_unnamed_attributes`. May drop this later in favor of just using `_unnamed_attributes` for those types.
 - Changed `DataList._serialize` and `DataDict._serialize` to utilize the `_serialize(alt_container)` feature described above
 - Changed `DataList.__getitem__` and `DataDict.__getitem__` to 
 - Refactored `FreezableMmifObject.deep_freeze` to use Pyrsistent data structures
 - Added optional `additional_containers` vararg parameter for naming any containers in `reserved_names` whose contents should be frozen. This is only used for freezing `FreezableDataList`s and `FreezableDataDict`s.
 - Refactored `MmifObject._serialize` to convert Pyrsistent data structures back into Python data structures for JSON dumping (does not unfreeze `self`--`_serialize` is still pure).
 - Added some additional tests to ensure `deep_freeze` returns correctly
 - Fixed a bug in `SubmediaList._deserialize` that was looking for a `"properties"` object (left over from copying the code from `AnnotationsList`)

**Comment by angus-lherrou** [comment]
@keighrim could you review my latest changes? I will fix the merge conflicts afterwards, so as to avoid commit clutter in this PR

**Review by keighrim — COMMENTED** [review]
All look good.

**Pull request merged**
