### PR TITLE
Implementation of MMIF vocabulary enum

### PR DESCRIPTION
**Pull request by angus-lherrou**
Users can utilize the AnnotationTypes enum in their code as shorthand for the MMIF URIs.

The enum is generated for the current **spec version** by `publish.py` at `mmif-python/mmif/vocab/annotation_types.py`.

It serializes into the full URI when exporting. Currently it is only intended as a developer shorthand, and URIs from MMIF files are not deserialized into enum objects.

This does not implement the scheme laid out in #64.

### CODE REVIEW

**Comment by angus-lherrou** [comment]
CI failed due to a feature in `datetime` that I used only being available in Python 3.7+.

Do we still want to target 3.6+?

**Comment by angus-lherrou** [comment]
There is this PyPI package, but it's in pre-alpha so we may not want to rely on it.

https://pypi.org/project/backports-datetime-fromisoformat/

**Comment by angus-lherrou** [comment]
I found a more mature package, https://pypi.org/project/python-dateutil/, that can replace `datetime.fromisoformat`.

**Comment by angus-lherrou** [comment]
Requesting reviews from Marc and Keigh because of the added dependency

**Comment by keighrim** [comment]
I'd like to support python 3.6 because the second-to-latest versions of two major linux distro, namely ubuntu 18.04 and cent/rhel7,  still ship 3.6 as the default python3. Unless we want to perform full-fledged ISO format parsing, I think we can use [this](https://docs.python.org/3.6/library/datetime.html#datetime.datetime.strptime) to reverse the `isoformat()` method.

**Comment by angus-lherrou** [comment]
[This answer](https://stackoverflow.com/a/30696682) on stackoverflow suggests that using strptime is a bad idea. I'm not sure if our usecase might mean that it's fine, though.

**Comment by keighrim** [comment]
I didn't see you already implemented parsing with `dateutil` before I left my previous comment. And yeah, that seems to be actually a better, robust solution.

**Comment by angus-lherrou** [comment]
I see pros and cons to both approaches.

So, with `strptime`, 
```python
self.gen_time = datetime.strptime(self.gen_time, "%Y-%m-%dT%H:%M:%S")
```
works for our current examples, and assuming we always generate our timestamps the same way and never expect to see timestamps generated by someone not using our code that might include milliseconds or offsets, it should be fine. Using `strptime` also saves us the added dependency.

One caveat with dateutil are these two notes in the documentation for `isoparse`:

```
.. caution::

    Support for fractional components other than seconds is part of the
    ISO-8601 standard, but is not currently implemented in this parser.

.. warning::

    As of version 2.7.0, the strictness of the parser should not be
    considered a stable part of the contract. Any valid ISO-8601 string
    that parses correctly with the default settings will continue to
    parse correctly in future versions, but invalid strings that
    currently fail (e.g. ``2017-01-01T00:00+00:00:00``) are not
    guaranteed to continue failing in future versions if they encode
    a valid date.
```

Is this something we care about?

**Comment by keighrim** [comment]
You already did a good job. Let's just keep it. I also think using `dateutil` is more future-proof anyway.

**Comment by keighrim** [comment]
Generation code as well as generated code all look good. One thing bothers me is that the generation happens while making `vocabulary` but the generated code is used in `mmif-python`. That means we need to make sure that whenever there's a new version of spec (`spec-x.y.z`) that involves update in vocabulary, we also MUST create a new version of the sdk with the newly generated `annotation_types.py`. I know we won't be updating the vocab so frequently, and thus we probably would be able to handle the release cycles by hand if we pay enough attentions. But it still bothers me...

**Comment by angus-lherrou** [comment]
That's a good point, and I had been thinking about that as well.

I suppose we could do what I had been doing with the pregenerated subtype thing a while back and do it in setup.py. We're still grabbing the latest `clams.vocabulary.yaml` there anyway and putting it in `res`, so that would work.

**Comment by keighrim** [comment]
Just added a commit that gives access to spec version by `mmif.__specver__` variable.

**Comment by angus-lherrou** [comment]
Awesome, thanks. Sorry about the confusing branch names.

**Comment by marcverhagen** [comment]
The parts related to the vocabulary that I looked at seem fine. Does the build mechanism include committing `annotation_types.py` after it is generated? Also, and this is rather nitpicky, that file says the content below line 14 is autogenerated, but the whole file is.

**Comment by angus-lherrou** [comment]
The build mechanism does not commit the file. I'm working on moving that mechanism into setup.py instead of publish.py, which would mean that the file gets generated when you build the python package, avoiding the need to commit the file, I think.

Fair nitpick--my reasoning was because the contents of the file above that line is from `annotation_types.txt` and not generated by the code. But it's a fair point, so I can put a comment at the top instead

**Comment by keighrim** [comment]
I'd like to suggest we rename the sub package name `vocab` into a full word `vocabulary`, as that package is a part of public API and I think we want to be consistent between terms we use in specification and the sdk.

**Comment by marcverhagen** [comment]
> I'd like to suggest we rename the sub package name `vocab` into a full word `vocabulary`, as that package is a part of public API and I think we want to be consistent between terms we use in specification and the sdk.

I agree.

**Comment by angus-lherrou** [comment]
> I'd like to suggest we rename the sub package name `vocab` into a full word `vocabulary`, as that package is a part of public API and I think we want to be consistent between terms we use in specification and the sdk.

Making that change now

**Comment by angus-lherrou** [comment]
Alright this error is beyond me. Anyone know why the VERSION is getting replaced by "HEAD"?

**Comment by keighrim** [comment]
When the version given by `VERSION` file indicates it's a `dev` one, the setup.py will use git `HEAD` instead of a tag `spec-x.y.z` to checkout outside files (from other MMIF components) and pass `HEAD` as spec version (`mmif.__specver__`) to the distribution package. 
Anyway, I'll take it from here and make necessary fixes. Thanks for the work.

**Comment by keighrim** [comment]
d3972c68b842cb7fcab4734471260200f79a690b contains an ugly hack job to handle example json strings with varying spec version. This (maybe) can be improved when we work on #80.

**Pull request merged**
