### PR TITLE
(reverted) releasing 1.1.0

### PR DESCRIPTION
**Pull request by keighrim**
### Overview
This release includes an additional of an optional field, and clarification of `TimeFrame` types.

### Additions
* `view.matadata.refinedParameters` field (optional) is added for recording runtime parameters after they are "refined" (#208).
* vocabulary type can have `similarTo` field to provide URI's of similar type definitions (#203).

### Changes
* removed explicit restriction on types of `TimeFrame` annotation (#207).

### CODE REVIEW

**Comment by keighrim** [comment]
This has been open long enough. @marcverhagen I wonder if you have time for reviewing changes here any time soon. Otherwise, I'll just merge without additional verification.

**Review by marcverhagen — COMMENTED** [review]
Only a few remarks: all on the refined parameters section, which is not clear.

One detail is that they are not introduced in the JSON example.

Another is that the sentence  "The parameters is a dictionary of parameters and their values in string" would be clearer if changed into "The parameters is a dictionary of parameters and their string values".

I am also wondering whether it is needed. It now looks like a view has both the string-valued parameters that are handed in to the app as well as the refined values that the app creates automatically. Can't we just have the values in "parameter" be the converted  ones?

Finally, both parameters are defined in the same way and it looks like if data types are converted the JSON schema will not allow it.

**Comment by keighrim** [comment]
Pushed a commit fixing some problems pointed out in the comment. 

> Can't we just have the values in "parameter" be the converted ones?

Also added a sentence to the spec document to clarify this questions. Going back to the first discussion of this addition (https://github.com/clamsproject/clams-python/issues/166), I genuinely believe that we absolutely need to keep user input "as-is" for reproducibility and accountability.

**Review by marcverhagen — APPROVED** [review]
The schema are good now and the description of the parameters is much better, I would however revert "The refinedParameters is an object of parameters" back to "The refinedParameters is a dictionary of parameters". I had forgotten about the discussion we had on this in the past. I see how we want the parameters to contain the original ones as given by the user, but am not quite sure why we also need to keep track of the refined ones for reproducability. I wish we could find a more elegant way, but that should not hold up this release.

**Pull request merged**
